name: build

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: poetry run make lint
      - run: poetry build

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        sqlalchemy-version: ["1.3.0", "1.4.0", "2.0.0b4"]

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2.1

      - run: poetry install

      - name: Install specific sqlalchemy version
        run: poetry run pip install 'sqlalchemy~=${{ matrix.sqlalchemy-version }}'

      - run: poetry run make test

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.xml
