name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: dschep/install-poetry-action@v1.2
        with:
          version: 1.0.0a1
      - run: poetry run make test
